nickmarks-nav/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'welcome#index', as: :user_root
  post :incoming, to: 'incoming#create'

  resources :users, except: [:index]
  resources :bookmarks
  resources :bookmarks
  resources :welcome

  unauthenticated do
    root to: 'home#show', as: :unauthed_root
  end
end

nickmarks-nav/app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags

  # validates :url, :format => URI::regexp(%w(http https)), presence: true


  def tags_string
  	self.hashtags.map {|h| h.tag}.join(" ")
  end

  def tags_string=(values)
    # this is how you change the relation - right through the join table, without having to manipulate it directly
    self.hashtags = values.split(" ").map { |s| Hashtag.where(tag: s).first_or_create }
  end

  def self.create_through_email(user_email, tags, url)
    if user = User.where(email: user_email).first
      @bookmark = user.bookmarks.create(url: url, tags_string: tags) 
    end
	end

end

nickmarks-nav/app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_and_belongs_to_many :bookmarks 	
end

nickmarks-nav/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :bookmarks

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
end

nickmarks-nav/app/controllers/about_controller.rb
class AboutController < ApplicationController
end

nickmarks-nav/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

nickmarks-nav/app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	
  def bookmarks_params
    params.require(:bookmark).permit(:title, :tag_list)
  end
  
	def index
		if params[:tag]
			@bookmarks = Bookmark.tagged_with(params[:tag])
		else
			@bookmarks = Bookmark.all 
		end
	end

	def show
		@bookmark = Bookmark.find(params[:id])
	end

	def new
		@bookmark = Bookmark.new
	end

	def edit
		@bookmark = Bookmark.find(params[:id])
	end

	def create
		@bookmark = Bookmark.new(params[:bookmark])
		@bookmark.user = current_user
		if @bookmark.save
			redirect_to bookmarks_path, notice: "Bookmark was saved successfully"
		else
			flash[:error] =  "There was an error creating the bookmark"
			render new
		end
	end

	def update
		@bookmark = Bookmark.find(params[:id])
		if @bookmark.update_attributes(params[:bookmark])
			redirect_to bookmarks_path, notice: "Bookmark was updated successfully."
		else
			flash[:error] = "There was error updating the Bookmark, not sure what though"
			render :edit
		end
	end

	def destroy
		@bookmark = Bookmark.find(params[:id])
		name = @bookmark.title

    if @bookmark.destroy
      flash[:notice] = "\"#{name}\" bookmark was deleted successfully."
      redirect_to bookmarks_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :index
    end

	end


end

nickmarks-nav/app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
  end

end

nickmarks-nav/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

end

nickmarks-nav/app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]
  
  def my_library
    @user = User.find(params[:id])
    @my_bookmarks = @user.bookmarks
    authorize! :show, @user, message: "You need to be an account holder."
  end

  def favorites
    @user = User.find(params[:id])
    @favorited_bookmarks = Bookmark.favorited(current_user)
    authorize! :show, @user, message: "You need to be an account holder."
  end

  def show 
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    #decoded_body = nil
    sender = params['sender']
    subject = params['subject']
    body_plain = params["body-plain"]
    user = User.find_by_email  params["sender"]
    if !user  
      head 200 && return
    end
    
    tags_array = params["Subject"].scan(/#\w+/)
    
    hashtags = tags_array.map do |tag|
      Hashtag.first_or_create(title: tag)
    end

    url = /\b(([\w-]+:\/\/?|www[.])[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:<>"]\s]|\/)))/.match(params["body-plain"])
    
    bookmark = user.bookmarks.create(
      url: params[:"body-plain"], 
      hashtag_ids: hashtags.map(&:id))
    
    head 200
  end
end
  

nickmarks-nav/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

nickmarks-nav/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		@user.role = :member
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url, notice: "Thank you for signing up!"
		else
			render "new"
		end
		@user.update_attribute(:role, 'member')
	end

	def show
		@user = params[:id] ? User.find(params[:id]) : current_user

	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @bookmark.update_attributes(params[:bookmark])
			redirect_to @bookmark
		else
			flash[:error] = "Error saving bookmark. Please try again"
			render :edit
		end
	end

end

nickmarks-nav/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

nickmarks-nav/app/helpers/about_helper.rb
module AboutHelper
end

nickmarks-nav/app/helpers/application_helper.rb
module ApplicationHelper
end

nickmarks-nav/app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

nickmarks-nav/app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

nickmarks-nav/app/helpers/home_helper.rb
module HomeHelper
end

nickmarks-nav/app/helpers/incoming_helper.rb
module IncomingHelper
end

nickmarks-nav/app/helpers/users_helper.rb
module UsersHelper
end

nickmarks-nav/app/helpers/welcome_helper.rb
module WelcomeHelper
end

nickmarks-nav/app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>
<div class="col-md-8">
  <%= form_for @bookmark do |f| %>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
  <% end %>
</div>

nickmarks-nav/app/views/bookmarks/index.html.erb
<h1>My Bookmarks</h1>
<% @bookmarks.each do |bookmark| %>
<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img data-src="holder.js/300x300" alt="...">
      <div class="caption">
        <p><%= link_to bookmark.url, bookmark %> </p>
        <p><%= bookmark.hashtags.map(&:title).join(', ') %></p>
        
        <p><a href="bookmarks#edit" class="btn btn-primary" role="Edit">Edit</a> <a href="#" class="btn btn-default" role="Delete">Delete</a></p>
      </div>
    </div>
  </div>
</div>

<% end %>

nickmarks-nav/app/views/bookmarks/new.html.haml
%h1 Bookmarks#new
%p Find me in app/views/bookmarks/new.html.erb

nickmarks-nav/app/views/bookmarks/show.html.haml
%h1=  @bookmark.url
=  @bookmark.url 
=  @hashtags

<br>
<br>
= link_to "Edit", edit_bookmark_path, class: 'btn btn-success'
<br>
%p= button_to "Delete Nickmark", bookmark_path(@bookmark), data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger'

nickmarks-nav/app/views/hashtags/index.html.erb
<h1>Hashtags</h1>
<ul>
<% @hashtags.each do |hashtag| %>
  <li><%= link_to hashtag.name, hashtag_path(hashtag.name) %></li>
<% end -%>
</ul>

nickmarks-nav/app/views/hashtags/show.html.erb
<h1><%= params[:hashtag] %></h1>
<% if @hashtagged %>
  <% @hashtagged.each do |hashtagged| %>
    <%= render_hashtaggable hashtagged %>
  <% end -%>
<% else -%>
  <p>There is no match for the <em><%= params[:hashtag] %></em> hashtag.</p>
<% end -%>

nickmarks-nav/app/views/home/show.html.haml
%h1 Show

nickmarks-nav/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Nickmarks</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display
        -->
        <div class="navbar-header">
          <button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="bookmarks#index">Nickmarks</a>


        </div>
        <!-- Collect the nav links, forms, and other content for toggling
        -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
                  <li><a href="bookmarks#index">My Nickmarks</a></li>
            <li class="active"></li>
          </ul>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input class="form-control" placeholder="Search" type="text"> </input>
            </div>
            <button class="btn btn-default" type="submit">Goooo!</button>
          </form>

          <ul class="nav navbar-nav navbar-right"></ul>

        </div>
      </div>

    <div class="pull-right">
          <% if current_user %>
            Logged in as <%= link_to (current_user.name || current_user.email), current_user %>.
            <%= link_to "Log Out", destroy_user_session_path %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path %> or
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </div>
      </ul>

    </nav>
  </body>
  <%= yield %>
</html>

nickmarks-nav/app/views/users/my_library.html.haml
%h3 My Bookmarks
= render partial: "bookmarks/bookmark", collection: @my_bookmarks

nickmarks-nav/app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.erb
%body
  .fb-like{"data-share" => "true", "data-show-faces" => "true", "data-width" => "450"}

nickmarks-nav/app/views/welcome/about.html.haml
%h1 Nickmarks
%p#index-title Social Bookmarks

nickmarks-nav/app/views/welcome/index.html.haml
.jumbotron
  %h1 Nickmarks: Social Bookmarking
  .fb-like{"data-share" => "true", "data-show-faces" => "true", "data-width" => "450"}